---
# https://www.raspberrypi.com/tutorials/how-to-use-a-raspberry-pi-in-kiosk-mode/
- name: Copy labwc autostart file
  ansible.builtin.copy:
    src: autostart
    dest: /etc/xdg/labwc/autostart
    owner: root
    group: root
    mode: "0644"

# ? We need to set the language to Norwegian because info.phoenixlan.no has lang=nb
- name: Generate Norwegian Bokmål locale
  community.general.locale_gen:
    name:
      - "nb_NO.UTF-8"
    state: present
- name: Set system language to Norwegian Bokmål
  ansible.builtin.command: localectl set-locale LANG=nb_NO.UTF-8 LANGUAGE=nb_NO.UTF-8
  changed_when: false
