---
- name: Update cache & upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Register reboot requirement
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: check_reboot

- name: Reboot if needed
  ansible.builtin.reboot:
  become: true
  when: check_reboot.stat.exists
